# Generated by Django 5.2.11 on 2026-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_my_solution_project_problem_statement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=100)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
