# Generated by Django 5.2.11 on 2026-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education_alter_certificate_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='my_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='problem_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='task_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
