# Generated by Django 5.2.11 on 2026-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
